### ISSUE TITLE
Panic when stopping infinite attack

### ISSUE THREAD

**Issue by nakabonne** [nakabonne/ali#23]
```
ali/gui/keybinds.go:36
```

**Comment by brenol** [comment]
It's happening because of:
```
panic: send on closed channel

goroutine 84 [running]:
github.com/nakabonne/ali/gui.attack.func1(0x7ec980, 0xc00024a080, 0xc000254420, 0x7ffe01d5afea, 0x15, 0x32, 0x2540be400, 0x6fc23ac00, 0x7802fb, 0x3, ...)
	/home/brenol/goworkspace/src/github.com/brenol/ali/gui/keybinds.go:36 +0xd7
created by github.com/nakabonne/ali/gui.attack
	/home/brenol/goworkspace/src/github.com/brenol/ali/gui/keybinds.go:34 +0x19e
```
